
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    username: user
    password: password
    url: jdbc:h2:file:./database/h2.db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1

logging:
  level:
    org.hibernate.SQL: warn
    io.netty: warn
    org.springframework: warn
management:
  endpoints:
    web:
      exposure:
        include: '*'
